<?xml version="1.0" encoding="UTF-8"?><testrun name="MemManagerTest (1)" project="Project1" tests="10" started="10" failures="1" errors="0" ignored="0">
  <testsuite name="MemManagerTest" time="0.027">
    <testcase name="testPrintMemManager" classname="MemManagerTest" time="0.005"/>
    <testcase name="testInsertionSort" classname="MemManagerTest" time="0.005">
      <failure>junit.framework.AssertionFailedError: expected: &lt;true&gt; but was: &lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.TestCase.assertTrue(TestCase.java:192)&#13;
	at student.TestCase.assertTrue(TestCase.java:575)&#13;
	at student.TestCase.assertTrue(TestCase.java:597)&#13;
	at MemManagerTest.testInsertionSort(MemManagerTest.java:186)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)&#13;
	at student.testingsupport.junit4.RunTestMethodWrapper.evaluate(RunTestMethodWrapper.java:74)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)&#13;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#13;
	at java.base/java.lang.Thread.run(Thread.java:833)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testPrintOut" classname="MemManagerTest" time="0.001"/>
    <testcase name="testProcessFreeList" classname="MemManagerTest" time="0.002"/>
    <testcase name="testdoublesize" classname="MemManagerTest" time="0.002"/>
    <testcase name="testFindSpaceAvailable" classname="MemManagerTest" time="0.002"/>
    <testcase name="testgetNearestPowerOfTwo" classname="MemManagerTest" time="0.002"/>
    <testcase name="testsplitMemoryPool" classname="MemManagerTest" time="0.001"/>
    <testcase name="testdelete" classname="MemManagerTest" time="0.002"/>
    <testcase name="testdetectMerge" classname="MemManagerTest" time="0.002"/>
  </testsuite>
</testrun>
